## Exercise - 20180594 이정훈

1. Create len(10) integer array filled with zeros

In [4]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. Create 3x5 floating point array filled with ones

In [5]:
np.ones(15).reshape(3,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

3. Create 3x5 array filled with 3.14

In [39]:
a = np.arange(15.).reshape(3,5)
a.fill(3.14)
a

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

4. Create an array filled with a linear space starting at 0, ending at 20, stepping by 2

In [40]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

5. Create an array of five values evenly spaced between 0 and 1

In [41]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

6. Create a 3x3 array of uniformly distributed random (0, 1)

In [43]:
from numpy import random as rnd
rnd.uniform(low=0, high=1, size=9).reshape(3,3)

array([[0.80133735, 0.02588903, 0.26360767],
       [0.79384305, 0.62984164, 0.16974275],
       [0.13128571, 0.16695384, 0.58868704]])

7. Create a 3x3 array of with mean 0 and standard deviation 1

In [51]:
rnd.normal(size=9).reshape(3,3)

array([[ 0.10119649,  0.59815558, -2.9720092 ],
       [-0.01234272,  1.01277778,  0.58872594],
       [ 0.54770544,  0.46721317,  1.1745135 ]])

8. Create a 3x3 array of random integers in the interval [0, 10]

In [54]:
rnd.randint(low=0, high=10, size=9).reshape(3,3)

array([[1, 2, 5],
       [6, 1, 5],
       [9, 6, 3]])

9. Create a 3x3 identity matrix

In [57]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])